# Generated by Django 4.0.1 on 2022-01-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_commentaries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaries',
            new_name='CommentBest',
        ),
    ]
